site_title: Visual Essays
banner_image: https://picsum.photos/1200/225
base_url: https://jstor-labs.github.io/visual-essays
markup: 'markdown'
index: index.md
about: about.md
help: help.md
contact: contact.md
gh_path: https://jstor-labs.github.io/visual-essays
app_version: 0.2.6
visual_essays_version: 0.3.7
context: null
